name: CI
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type something to triggre manual jobs
        required: false
        default: ''
  pull_request:
    branches: [ master ]
    #paths:
    #  - '*.gradle'
    #  - 'src/**'
  push:
    branches: [ master ]
    paths:
      - '*.gradle*'
      - '**/src/**'
      - 'src/**'
jobs:
  tests:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.docker
            ~/.gradle
            !~/.gradle/checksums
            !~/.gradle/**/checksums
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/settings.gradle.kts', '**/build.gradle.kts') }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew --no-daemon dependencies
      - run: ./gradlew --no-daemon
  consul:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.docker
            ~/.gradle
            !~/.gradle/checksums
            !~/.gradle/**/checksums
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/settings.gradle.kts', '**/build.gradle.kts') }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew dependencies
      - run: ./gradlew --no-daemon up -Pdemonize=true
      - run: ./gradlew --no-daemon down
  dependency-updates:
    if: github.event.inputs.trigger != ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "Trigger: ${{ github.event.inputs.trigger }}"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.docker
            ~/.gradle
            !~/.gradle/checksums
            !~/.gradle/**/checksums
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/settings.gradle.kts', '**/build.gradle.kts') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew --no-daemon dependencyUpdates -Drevision=release
